version: "3"
services:
  php:
    build: .docker/php
    container_name: "apache-srv"
    image: server-apache
    volumes:
      - .docker/apache/fullchain.pem:/etc/ssl/certs/server.pem
      - .docker/apache/privkey.pem:/etc/ssl/private/server-key.pem
      - .docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./src:/var/www/html
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3309:3306"
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8089:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mynetwork
    

networks:
  mynetwork:
    driver: bridge
